import { StyleSheet, Platform, StatusBar } from "react-native"

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  header: {
    backgroundColor: "#007074",
    padding: 16,
    paddingTop: Platform.OS === "android" ? (StatusBar.currentHeight || 0) + 16 : 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
  },
  subtitle: {
    fontSize: 14,
    color: "#e6f2ff",
    marginTop: 4,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  statsText: {
    fontSize: 12,
    color: "#e6f2ff",
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  statusText: {
    fontSize: 12,
    color: "#e6f2ff",
  },
  cameraView: {
    backgroundColor: "#000",
    width: "85%",
    height: 280,
    borderWidth: 2,
    borderColor: "#007074",
    borderRadius: 20,
    overflow: "hidden",
    alignSelf: "center",
    marginVertical: 16,
    position: "relative",
  },
  scanFrame: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 200,
    height: 200,
    marginTop: -100,
    marginLeft: -100,
    borderWidth: 2,
    borderColor: "#00ff00",
    borderRadius: 10,
  },
  scanCorner: {
    position: "absolute",
    top: -2,
    left: -2,
    width: 20,
    height: 20,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderColor: "#00ff00",
  },
  scanOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  scanText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 10,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  button: {
    flex: 1,
    marginHorizontal: 2,
    backgroundColor: "#00879E",
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 50,
  },
  syncButton: {
    backgroundColor: "#27ae60",
  },
  clearButton: {
    backgroundColor: "#e74c3c",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 10,
    marginTop: 2,
  },
  listContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  listTitle: {
    fontSize: 18,
    fontWeight: "bold",
    padding: 16,
    backgroundColor: "#f9f9f9",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  listContent: {
    padding: 8,
  },
  itemContainer: {
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    marginVertical: 4,
    marginHorizontal: 8,
    flexDirection: "row",
    overflow: "hidden",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  itemContent: {
    flex: 1,
    padding: 12,
  },
  itemData: {
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 4,
  },
  itemType: {
    fontSize: 12,
    color: "#666",
    marginBottom: 2,
  },
  itemTime: {
    fontSize: 10,
    color: "#999",
  },
  itemActions: {
    flexDirection: "column",
  },
  copyButton: {
    backgroundColor: "#71BBB2",
    justifyContent: "center",
    alignItems: "center",
    width: 50,
    flex: 1,
  },
  deleteButton: {
    backgroundColor: "#e74c3c",
    justifyContent: "center",
    alignItems: "center",
    width: 50,
    flex: 1,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  emptyText: {
    fontSize: 16,
    color: "#999",
    marginTop: 16,
    textAlign: "center",
  },
  emptySubtext: {
    fontSize: 14,
    color: "#ccc",
    marginTop: 8,
    textAlign: "center",
  },
})

export default styles